import sqlite3 as sql
import fso_td_init as init

def init_ai():
    database = sql.connect('db/fso_td.db')

    db = database.cursor()


    # Add AI table items
    db.execute(
        """
        INSERT INTO items(item_text, documentation, info_type, major_version_added, table_id) VALUES
        ("$Name:", "Defines a name for the AI class that can be used with ships.tbl and also with FRED", "TEXT", "2.0", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("+nocreate", "Allows editing of the AI class entry without creating a new entry","NULL","23.2", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Accuracy:", "Allows editing of the AI class entry without creating a new entry","FLOAT_LIST5","23.2", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Evasion:", "How good the ship is at evading. Value defines the frequency of AI course changes while it is evading.", "FLOAT_LIST5", "2.0", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Courage:", "How likely the ship is to chance danger to accomplish goals. Basically the lower the value sooner the AI will start evading when attacked and its less likely to target turrets.", "FLOAT_LIST5", "2.0", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Patience:", "How willing the ship is to wait for an advantage before pursuing goals. Implemented in 3.6.12 in conjunction with the $Stalemate Time Threshold and $Stalemate Distance Threshold options, otherwise does nothing.", "FLOAT_LIST5", "2.0", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Afterburner Use Factor:", "Affects how probably it is that the AI will use afterburners in 'maybe' situations. A value of 1 means always, 2 means half the time, 3 a third of the time, etc.", "INT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Shockwave Evade Chances Per Second:", "Controls how likely it is for a ship to try to start evading a shockwave. The higher the number, the more 'chances per second' the ship has to evade.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Get Away Chance:", "How likely the AI is to use a 'get away' maneuver instead of simply making evasive turns. 'Get away' usually involves the AI flying straight away, usually on afterburner, and making small jinking motions (instead of large evasive turns). Higher values result in more 'jousting' fights. 0.0 is never, 1.0 is always.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Secondary Range Multiplier:", "Multiplier which affects from how far away the AI will begin firing secondary weapons. Capped by the actual maximum range of the weapon. Penalty for firing in nebula still applies above and beyond this. 0.0 never, 1.0 from max distance.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Autoscale by AI Class Index:", "If set to YES (default), a number of miscellaneous AI probabilities are affected by the order of the AI class in the file (for example, the chance to fire countermeasures). Classes near the beginning of the file are generally weaker than classes at the end. If set to NO, this flag will turn off that auto scaling behavior (so that the order of the AI class does not affect AI behavior).\n\nNote that even if this is set to NO, the other options above will still be controlled by AI class index (so if you want complete independence, you need to set all of the options listed in the 'Other AI Class Attributes' category).", "BOOL_YESNO", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$AI Countermeasure Firing Chance:", "Overrides the AI_Profiles value for this AI class. Defines the chance a countermeasure will be fired by an AI-controlled ship (scaled by $Autoscale by AI Class Index:). ", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$AI In Range Time:", "Overrides the AI_Profiles value for this AI class. The delay (in seconds) for the AI to fire its weapons after getting in range.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$AI Always Links Ammo Weapons:", "Overrides the AI_Profiles value for this AI class. AI ships will link ballistic primaries if ammo levels are greater than these percents.", "FLOST_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$AI Maybe Links Ammo Weapons:", "Overrides the AI_Profiles value for this AI class. Defines the same as $AI Always Links Ammo Weapons: but in situations when its hull is below 33 % of maximum hitpoints. Overrides ai_profiles entry.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Predict Position Delay:", "Overrides the AI_Profiles value for this AI class. Sets the time after which the AI will recalculate the position of its target.\n\nIt does not apply to the AI's aim, it only applies to things like avoiding collisions and maneuvering at close range. Generally, anything other than a 0 just allows the AI to do monumentally stupid things like try to turn to avoid ramming where it thought you were 2 seconds ago.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$AI Shield Manage Delay:", "Overrides the AI_Profiles value for this AI class. Sets the time in seconds between each instance of an AI ship managing its shields", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Friendly AI Fire Delay Scale:", "Overrides the AI_Profiles value for this AI class. Sets the factor applied to 'fire wait' for friendly ships.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Hostile AI Fire Delay Scale:", "Overrides the AI_Profiles value for this AI class. Sets the factor applied to 'fire wait' for hostile ships", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$AI Turn Time Scale:", "Overrides the AI_Profiles value for this AI class. Defines the factor applied to time it takes for enemy ships to turn. A value of 1.0 means the ship turns at normal speed, 2.0 means half speed (takes twice as long), etc. Note that this value ONLY affects ships hostile to the player (always 1.0 for friendly ships).", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Glide Attack Percent:", "Overrides the AI_Profiles value for this AI class. How often the AI will use the 'glide attack' move when it has the opportunity. Glide attack means using glide to maintain course while aiming and firing at the current target. Only affects ships capable of glide.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Circle Strafe Percent:", "Overrides the AI_Profiles value for this AI class. How often the AI will use the 'circle strafe' move when it has the opportunity. Circle strafe means that the ship will attempt 'Descent-like' combat, trying to maintain distance while circling around the target using sidethrusters. Ships will only attempt this when sidethrust top speed is at least 2/3 of target's current velocity.", "FLOAT_LIST5", "2.0", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Glide Strafe Percent:", "Overrides the AI_Profiles value for this AI class. How often the AI will use the 'glide strafe' move when it has the opportunity. Glide strafe means using glide to attack capships by flying past and shooting at them. Only affects ships capable of glide.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Stalemate Time Threshold:", "Overrides the AI_Profiles value for this AI class. The minimum amount of time required for the AI to detect a 'stalemate' situation. If a ship and its target have been within a certain distance of each other (defined by $Stalemate Distance Threshold) for this amount of time without either of them scoring a hit on the other, the AI will do something to break the stalemate. Only applies to small ships. If this value is 0 or less, no stalemate detection is performed.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Stalemate Distance Threshold:", "Overrides the AI_Profiles value for this AI class. The maximum distance that an AI ship must remain from its target for a 'stalemate' to occur (see $Stalemate Time Threshold).", "FLOAT_LIST5", "3,6,12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Chance AI Has to Fire Missiles at Player:", "Overrides the AI_Profiles value for this AI class. Chance for an AI to hesitate about firing a secondary or homing turret weapon at the player. Values range from 0-6, at 0 they will frequently hesitate, at 6 they will never hesitate.\n\nMechanic details: AIs are only allowed to fire homing secondaries or turrets with homing weapons at the player in a limited window of time. The window starts every ten seconds, and lasts (value + 1) 7ths of that ten second cycle. Each ship has it's own cycle, so their windows are not all synchronized.", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Max Aim Update Delay:", "Overrides the AI_Profiles value for this AI class. Maximum amount of delay allowed before the AI will update its aim. Until the next update, the AI will project the target forward based on last checked position and velocity. Applies to small ships vs small ships (dogfights). The actual delay is randomly selected between 0 and the maximum (so setting a value of 2 will result in an average of 1 second delay).", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$Turret Max Aim Update Delay:", "Overrides the AI_Profiles value for this AI class. As $Max Aim Update Delay, but affecting turrets instead", "FLOAT_LIST5", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$big ships can attack beam turrets on untargeted ships:", "Overrides the AI_Profiles value for this AI class. If set, big ships can attack a beam turret that's firing on them from a ship that they don't currently have targeted.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$smart primary weapon selection:", "Overrides the AI_Profiles value for this AI class. If set, enables the new primary weapon selection method", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$smart secondary weapon selection:", "Overrides the AI_Profiles value for this AI class. If set, enables the new secondary weapon selection method (including proper use of bomber+ missiles)", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$smart shield management:", "Overrides the AI_Profiles value for this AI class. If set, shields will devote all their charging energy to the weakest quadrant(s) and not waste energy on fully-charged quadrants (previously was -smart_shields on the command line)", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$smart afterburner management:", "Overrides the AI_Profiles value for this AI class. If set, the AI will properly use brief pulses of afterburner power instead of afterburning until fuel is exhausted.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$allow rapid secondary dumbfire:", "Overrides the AI_Profiles value for this AI class. If set, allows an AI ship to switch to rapid fire for dumbfire missiles.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$huge turret weapons ignore bombs:", "Overrides the AI_Profiles value for this AI class. If set, causes huge turret weapons (including anti-capship beams) to not target bombs.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$don't insert random turret fire delay:", "Overrides the AI_Profiles value for this AI class. If set, removes the random turret fire delay (from .1 to .9 seconds) inserted in addition to AI Fire Delay Scale.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$prevent turrets targeting too distant bombs:", "Overrides the AI_Profiles value for this AI class. If set, prevents turrets from targeting bombs beyond maximum range of the weapons of the turret..", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$smart subsystem targeting for turrets:", "Overrides the AI_Profiles value for this AI class. If set, prevents turrets from trying to target subsystems beyond their fov limits, also keeps the turret subsystem targeting preference order intact regardless of the angle to the target.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$allow turrets target weapons freely:", "Overrides the AI_Profiles value for this AI class. If set, allows turrets to target any weapons instead of just targeting bombs, to be used in conjunction with target priorities setup.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$allow vertical dodge:", "Overrides the AI_Profiles value for this AI class. If set, allows ships to dodge weapons fire vertically as well as horizontally.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$No extra collision avoidance vs player:", "Overrides the AI_Profiles value for this AI class. If set, allows ships to dodge weapons fire vertically as well as horizontally.", "BOOL_FLEX", "3.6.12", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$all ships manage shields:", "Overrides the AI_Profiles value for this AI class. Allows AI to manage shields on big ships", "BOOL_FLEX", "3.6.14", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$ai can slow down when attacking big ships:", "Overrides the AI_Profiles value for this AI class. When set, fighters attacking big ships will slow down depending on how long they've been attacking (80% speed after 5 seconds, 60% after 8 seconds, 40% after 10 seconds, and 20% after 15 seconds), how long it's been since they were last shot (full throttle if it was within the past 6 seconds), and how close they are (full throttle if the target is more than 1200 meters away).", "BOOL_FLEX", "3.8.0", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)),
        ("$use actual primary range:", "Overrides the AI_Profiles value for this AI class. When set, fighters will no longer fire primary weapons at targets outside their range just because weapon travel time would be sufficiently short.", "BOOL_FLEX", "19.0", (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1))        
        """
    )

    ### Uncomment to test ai table population.
    #test = db.execute("SELECT * FROM items WHERE table_id = (SELECT table_id FROM tables WHERE filename = 'Ai' LIMIT 1)")
    #
    #for item in test:
    #    print(item)


### Uncomment to test table population.
#test = db.execute("SELECT * FROM tables")
#
#for item in test:
#    print(item)
